name: Build and Deploy Hugo Site

on:
  push:
    branches: [ main ]
    paths:
      - 'ohmygo.ru/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ohmygo.ru/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: serg3091/ohmygo.ru

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./ohmygo.ru
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update deployment image
      if: github.ref == 'refs/heads/main'
      run: |
        sed -i "s|image: serg3091/ohmygo.ru:.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|" ohmygo.ru-k8s/k8s/deployment.yaml
        
    - name: Commit updated deployment
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ohmygo.ru-k8s/k8s/deployment.yaml
        git diff --staged --quiet || git commit -m "Update deployment image to ${{ github.sha }}"
        git push