name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build Hugo Site"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
        repository: SergeyParamoshkin/ohmygo
        path: ohmygo

    - name: Get build info
      id: build-info
      run: |
        echo "sha=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT
        echo "image=ghcr.io/sergeyparamoshkin/ohmygo.ru:${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT

    - name: Update deployment image
      run: |
        cd ohmygo
        sed -i "s|image: .*ohmygo.ru:.*|image: ${{ steps.build-info.outputs.image }}|" ohmygo.ru-k8s/k8s/deployment.yaml

    - name: Commit updated deployment
      run: |
        cd ohmygo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ohmygo.ru-k8s/k8s/deployment.yaml
        git diff --staged --quiet || git commit -m "Update deployment image to ${{ steps.build-info.outputs.sha }}"
        git push